# Generated by Django 4.2.1 on 2023-06-15 23:29

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Clase1",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("campo1", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="Clase2",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("campo1", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="Clase3",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("campo1", models.CharField(max_length=100)),
            ],
        ),
    ]
